<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOtuflaa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOtuflaa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOtuflaa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOtuflaa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOtuflaa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Otuflaa',
    'container.build_id' => 'efa1a7fc',
    'container.build_time' => 1563371375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOtuflaa');
