<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'commande.food' => [['id'], ['_controller' => 'App\\Controller\\CommandeController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Commander']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/Contact']], [], []],
    'food' => [[], ['_controller' => 'App\\Controller\\FoodController::index'], [], [['text', '/Restaurant']], [], []],
    'news' => [[], ['_controller' => 'App\\Controller\\NewsController::index'], [], [['text', '/news']], [], []],
    'page_principal' => [[], ['_controller' => 'App\\Controller\\PagePrincipalController::index'], [], [['text', '/Coworking-Gusto']], [], []],
    'panier' => [['id'], ['_controller' => 'App\\Controller\\PanierController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier']], [], []],
    'panier.delete' => [['id'], ['_controller' => 'App\\Controller\\PanierController::deletePanier'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/panier']], [], []],
    'private' => [[], ['_controller' => 'App\\Controller\\PrivateController::index'], [], [['text', '/Salons-Privées']], [], []],
    'reservation.priv' => [['id'], ['_controller' => 'App\\Controller\\PrivateController::reservation'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/Reservation']], [], []],
    'public' => [[], ['_controller' => 'App\\Controller\\PublicController::index'], [], [['text', '/Espace-Public']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/Inscription']], [], []],
    'reservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/Connexion']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'app_edit' => [['id'], ['_controller' => 'App\\Controller\\SecurityController::UpdateUsers'], [], [['variable', '-', '[^/]++', 'id', true], ['text', '/Mon-Compte']], [], []],
];
